-- ============================================================================
-- ONE App v1.8 — Payment Advice tracking table
-- File:  SQL Files/12_BN_PaymentAdvice.sql
-- Date:  2026-06-04
--
-- WHY:
--   Customers who pay us get an acknowledgement WhatsApp + PDF "Payment Advice"
--   showing the amount we received and which Sales Invoices it was applied to.
--   This table tracks which NAV payment entries have already been advised so
--   the daily cron never double-sends. Same pattern as BN_ReminderLog tracks
--   reminder sends + BN_PDC tracks post-dated cheques.
--
--   The CANONICAL reference on every advice is NAV's own Payment Document No.
--   (e.g. "COMPANYA/26/27/02346") taken straight from Cust_ Ledger Entry.Document_No_
--   — no separate advice-number sequence is generated by ONE App.
--
-- DATA SOURCES (NAV — read only):
--   - Cust_ Ledger Entry   WHERE [Document Type] = 1  (1 = Payment in NAV)
--   - Detailed Cust_ Ledg_ Entry  (UNION forward + reverse — see
--     reference_nav_dcle_apply_direction memory; the lookup pattern is
--     already used in modules/sales/routes/customers.js ledger query)
--   - Bank Acc_ Ledger Entry  (joined via [Bal_ Account No_] for bank + UTR)
--
-- SCOPE:
--   - WhatsApp send only to customers in REMINDER_WHATSAPP_* env whitelist
--     (matches existing payment-reminder scope per project_companya_whatsapp).
--   - PDF generation runs on-demand for ANY customer when accounts clicks
--     the new 📄 Receipt icon in Customer Ledger; no whitelist gate on PDF.
--
-- SAFETY:
--   - BizNAV_App only. NAV DB (NAV_Live) is touched read-only.
--   - IF NOT EXISTS guarded — re-running is a no-op.
--   - Additive table; no existing rows to lose.
-- ============================================================================

USE BizNAV_App;
GO

SET XACT_ABORT ON;
GO

IF OBJECT_ID('[dbo].[BN_PaymentAdvice]', 'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[BN_PaymentAdvice] (
        Id                    INT             IDENTITY(1,1) PRIMARY KEY,

        -- Source company + customer (denormalised snapshot at advice time).
        Company               NVARCHAR(10)    NOT NULL,         -- 'COMPANYA' / 'CompanyB'
        CustomerCode          NVARCHAR(20)    NOT NULL,         -- NAV Customer.[No_]
        CustomerName          NVARCHAR(200)   NULL,             -- snapshot

        -- Payment identity — the dedup key. PaymentEntryNo is monotonic + unique
        -- within a company in NAV; PaymentDocNo is the human-readable label that
        -- appears on the PDF + WhatsApp message body.
        PaymentEntryNo        INT             NOT NULL,         -- NAV CLE.[Entry No_]
        PaymentDocNo          NVARCHAR(50)    NOT NULL,         -- 'COMPANYA/26/27/02346'
        PaymentDate           DATE            NOT NULL,         -- NAV [Posting Date]
        Amount                DECIMAL(18, 2)  NOT NULL,         -- absolute (positive) value

        -- Payment metadata (sourced from NAV Bank Acc_ Ledger Entry where available).
        PaymentMode           NVARCHAR(30)    NULL,             -- 'Bank' / 'Cheque' / 'NEFT' / 'UPI' / 'Cash'
        Reference             NVARCHAR(100)   NULL,             -- UTR / cheque no / txn id (from [External Document No_])
        BankName              NVARCHAR(200)   NULL,             -- bank + branch when from bank ledger

        -- Snapshot of applied invoices at advice time, as JSON. Each element:
        --   { "InvoiceNo": "COMPANYA/BE-2526/0985",
        --     "InvoiceDate": "2025-08-28",
        --     "OriginalAmount": 8250.00,
        --     "AppliedAmount":  8250.00 }
        -- We store the snapshot (not just an FK) so the PDF can be regenerated
        -- exactly even if the NAV row is later edited or re-applied.
        AppliedInvoicesJson   NVARCHAR(MAX)   NULL,

        -- Generated PDF — relative URL under backend/uploads/payment-advice/...
        PdfUrl                NVARCHAR(500)   NULL,

        -- WhatsApp send state (mirrors BN_ReminderLog).
        WhatsAppPhoneTo       NVARCHAR(20)    NULL,
        WhatsAppMessageId     NVARCHAR(100)   NULL,             -- Meta's wamid after send
        WhatsAppSentAt        DATETIME2(0)    NULL,
        WhatsAppError         NVARCHAR(500)   NULL,             -- error text if status='failed'

        -- Lifecycle: pending → sent | failed | skipped | test_mode.
        --   pending    — cron picked it up, advice generated, send queued
        --   sent       — WhatsApp delivered (we have wamid)
        --   failed     — Meta API returned an error (WhatsAppError populated)
        --   skipped    — customer NOT in whitelist; PDF only
        --   test_mode  — REMINDER_TEST_MODE=true at cron run (log-only)
        Status                NVARCHAR(20)    NOT NULL DEFAULT 'pending',

        CreatedAt             DATETIME2(0)    NOT NULL DEFAULT SYSDATETIME(),
        UpdatedAt             DATETIME2(0)    NULL,

        -- Filtered + supporting indexes:
        --   UQ_*       — hard dedup. Cron's "NOT EXISTS" check joins on this.
        --   IX_Status  — pending/test-mode lookups when cron retries failed sends.
        --   IX_Cust    — Customer Ledger page reverse-lookup (advice list per customer).
        --   IX_Doc     — quick lookup by NAV doc no when frontend hits /payments/:docNo/pdf.
        INDEX UQ_BN_PaymentAdvice_Company_Entry UNIQUE  (Company, PaymentEntryNo),
        INDEX IX_BN_PaymentAdvice_Status                (Company, Status, CreatedAt),
        INDEX IX_BN_PaymentAdvice_Customer              (Company, CustomerCode, PaymentDate DESC),
        INDEX IX_BN_PaymentAdvice_Doc                   (Company, PaymentDocNo)
    );
    PRINT '[OK] dbo.BN_PaymentAdvice created.';
END
ELSE
    PRINT '[SKIP] dbo.BN_PaymentAdvice already exists.';
GO
